server:
    port: 7768
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true